#!/usr/pkg/bin/perl
use strict;
use Getopt::Std;
use POSIX qw( SIGKILL );


sub warnTimeout($$$$){
    my ($pid)	  = shift;
    my ($TIMEOUT) = shift;
    # just for information
    my ($url) 	  = shift;
    my ($caller)  = shift;        

    my $timeout = 0;
    eval {
        local $SIG{ALRM} = sub { $timeout = 1; alarm 0;};
        alarm($TIMEOUT);
        while(!$timeout) {
            last if waitpid($pid, POSIX::WNOHANG);
            sleep(1); }   };
    if ($@) {warn "Error:".$@;}
    if ($timeout) {
        kill(SIGKILL, $pid);
        warn " *****  TIMEOUT : $caller : $url";
    }
    alarm 0;
}

our(@ARGV);
our(%opts);

my ($URL);
my ($timeout);
my ($command_line);

getopts('ht:u:', \%opts);
print $opts{'h'};

#if (@ARGV) { $command_line = join ' ', @ARGV; }
#else { die 'You need command_line string',"\n";}
# print $command_line,"\n";

if ($opts{'t'}) { $timeout = $opts{'t'};}
if ($opts{'u'}) { $URL     = $opts{'u'};}
$command_line = 'curl ' . $URL;
print STDERR sprintf("%04d %s\n", __LINE__, $command_line);
my($curl) =  open(CURL, "$command_line 2>&1|") ; #|| print STDERR __FILE__
    my @LINES;
    while(<CURL>){
	push(@LINES, $_);
    } 
    close (CURL);

my ($w3m) =  open (W3M, "|w3m -T text/html");

my($pid) = fork() ;
if (!defined $pid) { die __FILE__,' ', sprintf("%4d <", __LINE__ ),  (caller 0)[3], '>:', (caller 0)[2], ' ', "\n";}
if ($pid == 0 ) {  # child
#	print STDERR __FILE__,' ', sprintf("%4d <", __LINE__ ),  (caller 0)[3], '>:', (caller 0)[2], 'pid (',$pid,') ', "\n";

    foreach my $line (@LINES) {
	print W3M;
    }
    close(W3M);
} else { # parent
#    print STDERR __FILE__,' ', sprintf("%4d <", __LINE__ ),  (caller 0)[3], '>:', (caller 0)[2], 'pid (',$pid,') ', "\n";    
    warnTimeout($w3m, $timeout, $command_line, (caller 0)[2]);  # set timeout
#    print STDERR __FILE__,' ', sprintf("%4d <", __LINE__ ),  (caller 0)[3], '>:', (caller 0)[2], 'pid (',$pid,') ', "\n";        
}

__END__
  print STDERR sprintf("%4d <", __LINE__ ),  (caller 0)[3], '>:', (caller 0)[2], ' ',

   37  perl fork-w3m  -t 1  w3m -T TEXT ftp://ftp.gnome.org/pub/GNOME/sources/at-spi2-atk/ > /dev/null
   38  perl fork-w3m  -t 3  w3m -T TEXT ftp://ftp.gnome.org/pub/GNOME/sources/at-spi2-atk/ > /dev/null
   39  perl fork-w3m  -t 10  w3m -T TEXT ftp://ftp.gnome.org/pub/GNOME/sources/at-spi2-atk/ > /dev/null
   40  perl fork-w3m  -t 10  w3m -T TEXT ftp://ftp.gnome.org/pub/GNOME/sources/at-spi2-atk/ 


SX3@makoto 19:25:25/220527(..x11/gnome-themes)% 

perl /export/git-work/check-update/fork-w3m -t 10  -u  ftp://ftp.gnome.org/pub/GNOME/sources/at-spi2-atk/
0046 curl ftp://ftp.gnome.org/pub/GNOME/sources/at-spi2-atk/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to ftp.gnome.org port 21 after 541 ms: Connection refused
 *****  TIMEOUT :  : curl ftp://ftp.gnome.org/pub/GNOME/sources/at-spi2-atk/ at /export/git-work/check-update/fork-w3m line 24.


 perl /export/git-work/check-update/fork-w3m -t 60 -u https://mirror.umd.edu/gnome/sources/caribou/
